import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:radhe/models/quotation_model.dart';

class QuotationPdfGenerator {
  static final _fmt = NumberFormat('#,##,##0.00', 'en_IN');

  // Column widths (pts). A4 content width = 595 - 60 margins = 535pt.
  static const double _c0 = 26;  // SR NO
  static const double _c1 = 85;  // ITEM DESC
  static const double _c2 = 36;  // GRADE
  static const double _c3 = 58;  // SIZE
  static const double _c4 = 74;  // IMAGE
  static const double _c5 = 76;  // QTY
  static const double _c6 = 76;  // RATE
  static const double _c7 = 78;  // FINAL AMOUNT
  static const double _tw = _c0 + _c1 + _c2 + _c3 + _c4 + _c5 + _c6 + _c7; // 509

  static Future<pw.Document> buildDocument(QuotationModel quotation) async {
    final pdf = pw.Document();

    // Load Noto Sans — supports ₹ and all Indian locale characters
    final fontRegular = await PdfGoogleFonts.notoSansRegular();
    final fontBold = await PdfGoogleFonts.notoSansBold();

    // Load logo
    final logoData = await rootBundle.load('assets/png/app_logo.png');
    final logoImage = pw.MemoryImage(logoData.buffer.asUint8List());

    // Pre-load all item images
    final Map<String, pw.MemoryImage> imgCache = {};
    for (final cat in quotation.categories) {
      for (final item in cat.items) {
        if (item.image != null) {
          final path = item.image!.path;
          if (!imgCache.containsKey(path)) {
            final bytes = await item.image!.readAsBytes();
            imgCache[path] = pw.MemoryImage(bytes);
          }
        }
      }
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        // Apply font globally so ₹ renders correctly on every widget
        theme: pw.ThemeData.withFont(
          base: fontRegular,
          bold: fontBold,
        ),
        build: (ctx) => _buildContent(quotation, logoImage, imgCache),
      ),
    );

    return pdf;
  }

  static Future<Uint8List> generate(QuotationModel quotation) async {
    final doc = await buildDocument(quotation);
    return doc.save();
  }

  // ── Page content ───────────────────────────────────────────────────────────

  static List<pw.Widget> _buildContent(
    QuotationModel q,
    pw.MemoryImage logo,
    Map<String, pw.MemoryImage> imgCache,
  ) {
    final widgets = <pw.Widget>[];
    int sr = 1;

    // Cover
    widgets.add(_cover(logo, q));
    widgets.add(pw.SizedBox(height: 12));

    // Table header
    widgets.add(_headerRow());

    // Items
    for (final cat in q.categories) {
      widgets.add(_categoryNameRow(cat.name));
      for (final item in cat.items) {
        final img = item.image != null ? imgCache[item.image!.path] : null;
        widgets.add(_itemRow(sr, item, img));
        sr++;
      }
      widgets.add(_subtotalRow(cat));
      widgets.add(pw.SizedBox(height: 4));
    }

    // Grand total
    widgets.add(pw.SizedBox(height: 8));
    widgets.add(_grandTotalWidget(q));

    return widgets;
  }

  // ── Cover ──────────────────────────────────────────────────────────────────

  static pw.Widget _cover(pw.MemoryImage logo, QuotationModel q) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Center(child: pw.Image(logo, width: 180, height: 180)),
        pw.SizedBox(height: 10),
        pw.Center(
          child: pw.Text(
            'RADHE TILES WORLD',
            style: pw.TextStyle(
              fontSize: 22,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.red800,
            ),
          ),
        ),
        pw.SizedBox(height: 6),
        pw.Center(
          child: pw.Text(
            'CONTACT NUMBER - 7389063094',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
        pw.SizedBox(height: 20),
        pw.Text('QUOTATIONS',
            style: pw.TextStyle(
                fontSize: 18, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 12),
        pw.Text('Date: ${DateFormat('M/d/yyyy').format(q.date)}',
            style: const pw.TextStyle(fontSize: 11)),
        pw.Text('Quotation ID: ${q.id}',
            style: const pw.TextStyle(fontSize: 11)),
        pw.Text('Generated By: ${q.generatedBy.toUpperCase()}',
            style: const pw.TextStyle(fontSize: 11)),
        pw.SizedBox(height: 8),
        pw.Text('Customer Name: ${q.customerName}',
            style: const pw.TextStyle(fontSize: 11)),
        if (q.phone.isNotEmpty)
          pw.Text('Phone: ${q.phone}',
              style: const pw.TextStyle(fontSize: 11)),
        if (q.address.isNotEmpty)
          pw.Text('Address: ${q.address}',
              style: const pw.TextStyle(fontSize: 11)),
        pw.SizedBox(height: 16),
        pw.Divider(thickness: 0.8),
      ],
    );
  }

  // ── Table rows ─────────────────────────────────────────────────────────────

  static pw.Widget _headerRow() {
    return pw.Container(
      height: 30,
      color: PdfColors.grey300,
      child: pw.Row(
        children: [
          _hCell(_c0, 'SR\nNO.'),
          _hCell(_c1, 'ITEM DESCRIPTION'),
          _hCell(_c2, 'GRADE'),
          _hCell(_c3, 'SIZE'),
          _hCell(_c4, 'IMAGE'),
          _hCell(_c5, 'QTY'),
          _hCell(_c6, 'RATE'),
          _hCell(_c7, 'FINAL AMOUNT'),
        ],
      ),
    );
  }

  static pw.Widget _categoryNameRow(String name) {
    return pw.Container(
      height: 22,
      width: _tw,
      color: PdfColors.grey100,
      alignment: pw.Alignment.center,
      child: pw.Text(
        name,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
      ),
    );
  }

  static pw.Widget _itemRow(int sr, QuotationItem item, pw.MemoryImage? img) {
    return pw.Container(
      height: 88,
      decoration: pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          _dCell(_c0, '$sr', center: true),
          _dCell(_c1, item.itemDescription),
          _dCell(_c2, item.grade, center: true),
          _dCell(_c3, item.size, center: true),
          // Image cell
          pw.Container(
            width: _c4,
            padding: const pw.EdgeInsets.all(3),
            decoration: const pw.BoxDecoration(
              border: pw.Border(
                right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
              ),
            ),
            child: img != null
                ? pw.Image(img, fit: pw.BoxFit.contain)
                : pw.Container(color: PdfColors.grey100),
          ),
          // QTY cell
          _multiCell(_c5, [
            if (item.sqft > 0) '${_fmt.format(item.sqft)} SQFT',
            '${item.boxes} Box',
          ]),
          // RATE cell
          _multiCell(_c6, [
            if (item.ratePerSqft > 0)
              '${_fmt.format(item.ratePerSqft)}/SQFT',
            '${_fmt.format(item.ratePerBox)}/Box',
          ]),
          _dCell(_c7, _fmt.format(item.finalAmount), center: true),
        ],
      ),
    );
  }

  static pw.Widget _subtotalRow(QuotationCategory cat) {
    return pw.Container(
      height: 20,
      color: PdfColors.grey50,
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Container(
              alignment: pw.Alignment.centerRight,
              padding: const pw.EdgeInsets.only(right: 6),
              child: pw.Text(
                "${cat.name}'s Total Amount (Incl. Tax)",
                style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, fontSize: 8),
              ),
            ),
          ),
          pw.Container(
            width: _c7,
            alignment: pw.Alignment.centerRight,
            padding: const pw.EdgeInsets.only(right: 6),
            child: pw.Text(
              _fmt.format(cat.totalAmount),
              style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold, fontSize: 9),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _grandTotalWidget(QuotationModel q) {
    return pw.Align(
      alignment: pw.Alignment.centerRight,
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        color: PdfColor.fromHex('122B84'),
        child: pw.Text(
          'Grand Total (Incl. Tax):  ₹${_fmt.format(q.grandTotal)}',
          style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
          ),
        ),
      ),
    );
  }

  // ── Cell helpers ───────────────────────────────────────────────────────────

  static pw.Widget _hCell(double w, String text) {
    return pw.Container(
      width: w,
      alignment: pw.Alignment.center,
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          right: pw.BorderSide(color: PdfColors.grey500, width: 0.5),
        ),
      ),
      child: pw.Text(
        text,
        textAlign: pw.TextAlign.center,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 7),
      ),
    );
  }

  static pw.Widget _dCell(double w, String text, {bool center = false}) {
    return pw.Container(
      width: w,
      alignment: center ? pw.Alignment.center : pw.Alignment.centerLeft,
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
      ),
      child: pw.Text(
        text,
        textAlign: center ? pw.TextAlign.center : pw.TextAlign.left,
        style: const pw.TextStyle(fontSize: 8),
      ),
    );
  }

  static pw.Widget _multiCell(double w, List<String> lines) {
    return pw.Container(
      width: w,
      alignment: pw.Alignment.centerLeft,
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 3),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
      ),
      child: pw.Column(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: lines
            .map((l) => pw.Text(l, style: const pw.TextStyle(fontSize: 8)))
            .toList(),
      ),
    );
  }
}
